#spring:
#  profile:
#    active:  dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/mydb
#    password: pass
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#some:
#  value:
#    url: "not a url"
#server:
#  port: '8082'
#---
#
#spring:
#  profile: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/mydb
#    password: pass
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#some:
#  value:
#    url: "not a url"
#server:
#  port: '8082'
